[workspace]
members = [
    "crates/cli",
    "crates/core",
    "crates/entity",
    "crates/migration",
    "crates/server",
    "crates/test"
]
default-members = ["crates/cli"]

[workspace.dependencies]
async-graphql = { version = "6.0.7", features = ["chrono", "decimal", "tracing"] }
async-trait = "0.1.73"
chrono = { version = "0.4.31" }
dotenv = "0.15.0"
pxid = { version = "0.3.0", features = ["async-graphql", "serde"] }
sea-orm = { version = "0.12.3" }
serde = { version = "1.0.188" }
serde_json = { version = "1.0.107" }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4.1", features = ["serde"] }
