[workspace]
members = [
    "src/core",
    "src/migration",
    "src/server",
]
default-members = ["src/server"]

[workspace.dependencies]
dotenv = "0.15.0"
tokio = "1.27.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.15"
url = { version = "2.3.1", features = ["serde"] }
