[package]
name = "linx"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
anyhow = "1.0.65"
axum = "0.5.16"
chrono = { version = "0.4.22", features = ["serde"] }
dotenv = "0.15.0"
rand = "0.8.5"
serde = { version = "1.0.144", features = ["derive"] }
sea-orm = { version = "0.9.2", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
tokio = { version = "1.21.0", features = ["rt", "rt-multi-thread", "macros"] }
tower-http = { version = "0.3.0", features = ["cors"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
uuid = { version = "1.1.2", features = ["serde"] }

# Local Crates
entity = { path = "entity" }
migration = { path = "migration" }
