name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Bun.sh
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.5.9

      - name: Install Dependencies
        run: bun i

      - name: Generate SvelteKit Directory
        run: bun run build

      - name: Run Tests
        run: bun run test
