[package]
name = "core"
version = "0.1.0"
edition = "2021"
authors = ["Esteban Borai <estebanborai@gmail.com>"]

[lib]
name = "gabble"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.71"
chrono = { version = "0.4.26", features = ["serde"] }
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.9.0"
rust-argon2 = "1.0.0"
sea-orm = { version = "0.11.2", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "mock" ] }
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.100"
tracing = "0.1.37"

# Workspace Dependencies
thiserror = { workspace = true }
pxid = { workspace = true }
url = { workspace = true }

# Local Dependencies
entity = { path = "../entity" }
migration = { path = "../migration" }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["rt", "macros"] }
